# action.yml
name: 'Talend Publish to Cloud Action'
description: 'Publish to TMC'
author: tgourdel

inputs:
  project: 
    description: 'Talend Cloud Project'
    required: true
  p2_url: 
    description: 'Talend Cloud Job version'
    required: true
  cloud_url: 
    description: 'Talend Cloud url'
    required: true
  cloud_token: 
    description: 'Talend Cloud Access token'
    required: true
  nexus_url: 
    description: 'Nexus URLS for custom libs and Maven plugins'
    required: true
  nexus_username: 
    description: 'Nexus username'
    required: true
  nexus_password: 
    description: 'Nexus passwords'
    required: true
  screenshot: 
    description: 'Publish screenshot to TMC'
    required: false
    default: 'true'
  license_path:
    description: 'Path of Talend license in your repository. Make sure to encrypt your license.'
    required: yes
    default: 'license.gpg'
  license_passphrase:
    description: 'Passphrase to decrypt Talend license in your repo. Make sure to store the passphrase in a secret.'
    required: yes

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'award'  
  color: 'green'